### ISSUE TITLE
Python module integration as submodule

### ISSUE THREAD

**Issue by marioangst** [marioangst/integrateR#2]
At the moment, the project is setup such as that sesmotifanalyser is integrated as a git submodule. Check if this is a proper way of integrating python modules in an R package.

**Comment by tseppelt** [comment]
The SMA module is now loaded by reticulate from PyPI using PIP when the package is installed. This is in line with https://blog.rstudio.com/2019/12/20/reticulate-1-14/ and hence most likely the optimal way to do it.

Having the submodule is no longer necessary for functionality. It might make sense to keep it in order to reuse data files from the SMA documentation (plots of motifs etc.) for the R documentation, but that's more a documentation issue, i.e. #4 .

**Comment by tseppelt** [comment]
Many features of sma required by the R side are not uploaded to PyPI yet. I don't want to waste version numbers. Clone the Gitlab repository separately and use the following command in the ``./sma`` directory.

```
rsync -v *.py ~/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/sma/
```
