### ISSUE TITLE
show_motif()

### ISSUE THREAD

**Issue by marioangst** [marioangst/integrateR#6]
We should have a function that displays the motif(s) based on their name, for convenience. At the moment, show_3_motifs or show_4_motifs just load images of all possible configurations from inst, but this does not scale and focal nodes are not shown.

**Comment by tseppelt** [comment]
The first implementation 8390d23 does not work for motifs which don't occur in the given network (because it relies on exemplify_motif). 

Positive: gives examples from the given network (real world examples). Works in full generality. Otherwise we would need to hard code all motifs (6 3-motifs, 28 4-motifs, 113 (2,2,1)-motifs, etc.).

Negative: doesn't work with motifs not existing in the network, rather slow because it has to find a motif first.

**Comment by marioangst** [comment]
Made a slightly prettier viz, but will generalize it later bf019ee57c0dbf545dab93c03bd3d5a469aa44ff
Regarding motifs not existing in the network: An idea would be to include a default example network for people working without an existing one, which supplies most motifs.

**Comment by marioangst** [comment]
generalized this in 24ba0931468f2b79899a03f9cc02d2faf0c39f56 - it looks pretty with two levels, have not checked with three yet

**Comment by tseppelt** [comment]
Todo: small example graph containing all motifs as default value
